# Generated by Django 2.1 on 2018-10-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('value', models.IntegerField()),
                ('balance_id', models.CharField(default='balance911b2ab274491be2790545e41', max_length=32, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotRegisterUser',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('verify_code', models.CharField(max_length=4, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('trade_type', models.IntegerField()),
                ('face_token', models.CharField(max_length=255, null=True)),
                ('trade_value', models.IntegerField()),
                ('trade_time', models.DateTimeField()),
                ('balance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance', to='chain.Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('order_id', models.CharField(default='order6fbfb08d47245d073921089efe9', max_length=32, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('transaction_value', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='user05fe729f2e93a71c67bb2af452d7', max_length=32, primary_key=True, serialize=False)),
                ('trade_id', models.CharField(max_length=32, null=True)),
                ('nick_name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('face_token', models.CharField(default='NULL', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriendRequestOrder',
            fields=[
                ('friend_order_id', models.CharField(default='ordera3724f8f674f176da28f729e6a8', max_length=32, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(default=True)),
                ('recipient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_receiver', to='chain.User')),
                ('sponsor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_sender', to='chain.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('another_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='another_user', to='chain.User')),
                ('one_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_user', to='chain.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='chain.User')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_receiver', to='chain.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_sender', to='chain.User'),
        ),
        migrations.AddField(
            model_name='trade',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='chain.Transaction'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance', to='chain.User'),
        ),
    ]
