# Generated by Django 2.1 on 2018-10-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_id',
            field=models.CharField(default='balance15e4bba933fd4ec8d3a6867f5', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default='orderc12e202aea52e411af5db13b8e1', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='usere299fe74022913b261e5e0ac0132', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfriendrequestorder',
            name='friend_order_id',
            field=models.CharField(default='order606af3323f18996d21e8a74300d', max_length=32, primary_key=True, serialize=False),
        ),
    ]
