# Generated by Django 2.1 on 2018-10-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_auto_20181021_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_id',
            field=models.CharField(default='balance0cbc411176ca0fd1327e4a6d2', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default='order1d1622edc0832756981781239a5', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='userb3d67a91f17083e817c7ef205b05', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfriendrequestorder',
            name='friend_order_id',
            field=models.CharField(default='orderee67188f8059cd4f66b9a0c3079', max_length=32, primary_key=True, serialize=False),
        ),
    ]
