# Generated by Django 2.1 on 2018-10-22 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_auto_20181022_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriendrequestorder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfriendrequestorder',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
