# Generated by Django 2.1 on 2018-08-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_friendmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendapply',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='chain.User'),
        ),
        migrations.AlterField(
            model_name='friendapply',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='chain.User'),
        ),
    ]
