# Generated by Django 2.1 on 2018-10-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_auto_20181022_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
