# Generated by Django 2.1 on 2018-08-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_auto_20180811_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmapping',
            name='another_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendmapping',
            name='one_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
