# Generated by Django 2.1 on 2018-09-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0005_auto_20180812_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
